{
 "title": "New dashboard",
 "time": { "from": "2023-02-27T00:37:40.631Z", "to": "2023-03-28T08:29:51.216Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  prediction_drift\nFROM dummy_metrics\n"
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  share_missing_values\nFROM dummy_metrics\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Median Fare Amount",
   "type": "timeseries",
   "description": "Fare Amount 0.5 Quantile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", median_fare_amount FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  num_drifted_columns\nFROM dummy_metrics\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1"
    }
   ]
  }
 ]
}